- name: Copy Dot Files
  tags: dotfiles
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: .config, dest: ~/ }
    - { src: .gitconfig, dest: ~/ }
    - { src: .tmux.conf, dest: ~/ }
    - { src: .vimrc, dest: ~/ }
    - { src: .zshrc, dest: ~/ }
